# Generated by Django 3.2.8 on 2021-10-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accountStatus',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Blocked')], default=1),
        ),
    ]
