# Generated by Django 3.2.8 on 2021-10-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_username_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='operation',
            field=models.IntegerField(choices=[(1, 'Logged in'), (2, 'Logged out'), (3, 'Updated Account Info'), (4, 'Deleted account'), (5, 'Created a new account')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'USER')], max_length=20),
        ),
    ]
