# Generated by Django 3.2.8 on 2021-10-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211022_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='operation',
            field=models.IntegerField(choices=[(1, 'Logged in'), (2, 'Logged out'), (3, 'Updated Account Info'), (4, 'Deleted account'), (5, 'Created a new account')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE'), (3, 'OTHER')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'USER')]),
        ),
    ]
